### ISSUE TITLE
re configure the bot

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Cool-Front-End-Templates#386]
## Issue Type:

- [x] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

In https://github.com/arpit456jain/Amazing-Js-Projects  the bot is adding the label when thePR is created but in this project its adding label when PR is merged 
figure it out why its happening and solve it

**Comment by TG922** [comment]
Hi @arpit456jain , Which label is being added by the bot when PR is merged??

**Comment by arpit456jain** [comment]
> Hi @arpit456jain , Which label is being added by the bot when PR is merged??

The label of GSSoC'22

**Comment by VidhiBhatt01** [comment]
@TG922 you want to work on this?

**Comment by TG922** [comment]
> @TG922 you want to work on this?

Yes for sure

**Comment by DEEPIKA-SUK** [comment]
@shilpiverma24 Go ahead

**Comment by Rakesh9100** [comment]
> 

Hello, I would like to suggest that I figured out here that In https://github.com/arpit456jain/Amazing-Js-Projects also the bot is adding the label when the PR is merged and not when it is opened and same with this project too. So, can I work on this issue or can I open up a new issue for the project https://github.com/arpit456jain/Amazing-Js-Projects so that label will be added when PR is opened ?

**Comment by Rakesh9100** [comment]
Hello, Can I work on this since it's more than 1-2 weeks ? Can it be assigned to me ?

**Comment by DEEPIKA-SUK** [comment]
@Rakesh9100 Go ahead and try to finish it in 2-3 days.
